version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev    
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
       url-auth0: http://localhost:3000/auth/callback'

